### ISSUE TITLE
Offline Payments missing in settings

### ISSUE THREAD

**Issue by jaiume** [akaunting/module-offline-payments#13]
### Akaunting version

3.1.6

### PHP version

8.1

### Operating system

Debian 10

### Steps to reproduce

New install of Akaunting 3.1.6
Navigate to Settings
Offline Payments missing from menu

### Expected result

Offline payments is visible

### Actual result

Offline Payments is missing
![Screenshot 2024-04-30 094217](https://github.com/akaunting/akaunting/assets/8379676/b912deb3-5528-43dc-8659-2fa191593b3e)

### Additional comments

Offline Payments Module is listed in the database with enabled set to 1

**Comment by jaiume** [comment]
Additional info

With Debug bar on, it says the gate 'read-offline-payments-settings' returns an error.

Database has no permissions definitions for offline payments settings. 

Adding them from other instance makes no difference though.

**Comment by cuneytsenturk** [comment]
https://github.com/akaunting/akaunting/commit/e8eeaf2bc2495b2b98edf1fc5fb8cf58f96496e5
